AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlMessagePeer");
AdfUIComponents.createComponentClass("AdfUIMessages",{componentType:"org.apache.myfaces.trinidad.Messages"});
AdfUIComponents.createComponentClass("AdfRichMessages",{componentType:"oracle.adf.RichMessages",propertyKeys:[{name:"inlineStyle",type:"String"},{name:"styleClass",type:"String"},{name:"shortDesc",type:"String"},{name:"unsecure",type:"Object",secured:!0},{name:"visible",type:"Boolean","default":!0},{name:"message",type:"String"},{name:"text",type:"String"},{name:"globalOnly",type:"Boolean","default":!1},{name:"inline",type:"Boolean","default":!1}],superclass:AdfUIMessages});
AdfRichUIPeer.createPeerClass(AdfRichUIPeer,"AdfDhtmlMessagesPeer");
AdfDhtmlMessagesPeer.InitSubclass=function(){AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.SHORT_DESC);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.MESSAGE);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.TEXT);AdfRichUIPeer.addComponentPropertyGetters(this,AdfRichMessages.GLOBAL_ONLY);AdfDhtmlMessagesPeer._ATTRIBUTE_GLOBAL_ONLY="_afrGlobalOnly";AdfDhtmlMessagesPeer._ATTRIBUTE_MESSAGE="_afrMessage";AdfDhtmlMessagesPeer._ATTRIBUTE_TEXT="_afrText";AdfDhtmlMessagesPeer._HEADER_TEXT_STYLE_CLASS=
"af|messages::header-text"};AdfDhtmlMessagesPeer.prototype.componentRemoved=function(a){AdfDhtmlMessagesPeer.superclass.componentRemoved.call(this,a);var b=AdfPage.PAGE,c=b.getDefaultMessageHandlerComponentId(),d=b.getMessageHandlerSlaveComponentId(),e=a.getClientId(),f=!1;if(e==c){for(var f=!0,g;a&&!g;)(a=a.getParent())&&a instanceof AdfRichDocument&&(g=a.getClientId());c=g}e==d&&(AdfMessageUtils.HideMessagesDialog(),f=!0,d=null);f&&b.setDefaultMessageHandlerComponentId(c,d)};
AdfDhtmlMessagesPeer.prototype.isMessagesDialogShowable=function(){return!1};AdfDhtmlMessagesPeer.prototype.setMessagesDialogShown=function(){};AdfDhtmlMessagesPeer.prototype.GetComponentShortDesc=function(a,b){return AdfAgent.AGENT.getAttribute(b,"title")};AdfDhtmlMessagesPeer.prototype.GetComponentMessage=function(a,b){return AdfAgent.AGENT.getAttribute(b,AdfDhtmlMessagesPeer._ATTRIBUTE_MESSAGE)};
AdfDhtmlMessagesPeer.prototype.GetComponentText=function(a,b){return AdfAgent.AGENT.getAttribute(b,AdfDhtmlMessagesPeer._ATTRIBUTE_TEXT)};AdfDhtmlMessagesPeer.prototype.GetComponentGlobalOnly=function(a,b){return AdfAgent.AGENT.getBooleanAttribute(b,AdfDhtmlMessagesPeer._ATTRIBUTE_GLOBAL_ONLY)};AdfDhtmlMessagesPeer.prototype.MessageShow=function(a,b){this._messageUpdate(a,b,!0)};
AdfDhtmlMessagesPeer.prototype.MessageNotify=function(a,b){AdfDhtmlMessagesPeer.superclass.MessageNotify.call(this,a,b);this._messageUpdate(a,b,!1)};
AdfDhtmlMessagesPeer.prototype._messageUpdate=function(a,b,c){var b=AdfPage.PAGE,d=this.getComponent(),e=d.getClientId(),f=b.getAllMessages(),g=this.getDomElement(),h=this.GetComponentGlobalOnly(d,g),k=f[e],l=0;if(k!=null)l=k.length;if(c&&!AdfMessageUtils.isPageLevelBoxNeeded(b,k,h))for(var m in f)c=f[m],c!=null&&c.compId!=null&&AdfMessageUtils.messageGroupFocus(m);if(AdfMessageUtils.hasMessages(b,l,h)){AdfDomUtils.removeAllNodes(g);m=AdfAgent.AGENT;c=m.getDomDocument().createElement("table");c.summary=
"";var n=c.insertRow(-1),l=n.insertCell(-1);a==null&&(a=0);if(h)a=k.maxType;else for(var o in f)k=f[o].maxType,k>a&&(a=k);o=AdfMessageUtils.getIcon(a,!0);l.appendChild(o);l=n.insertCell(-1);o=AdfPage.PAGE.getLookAndFeel();AdfDomUtils.addCSSClassName(l,o.getStyleClass(AdfDhtmlMessagesPeer._HEADER_TEXT_STYLE_CLASS));o=d.getText();o==null?m.setTextContent(l,AdfMessageUtils.getString(a,!0)):m.setTextContent(l,o);g.appendChild(c);a=d.getMessage();a=AdfMessageUtils.getCombinedMessagesDom(e,a,h);g.appendChild(a);
g.style.display=""}else AdfDomUtils.removeAllNodes(g),AdfMessageUtils.HideMessagesDialog();b.__queueDescendantResizeNotifySource(d);b.__doDescendantResizeNotify()};